services:
  redis:
    image: "redis:6"
    ports:
      - "6379:6379"
    networks:
      - network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - network
    depends_on:
      - redis
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  network:
    driver: bridge